apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: microservice-encoder
    name: microservice-encoder
  spec:
    replicas: 1
    selector:
      app: microservice-encoder
      deploymentconfig: microservice-encoder
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: microservice-encoder
          deploymentconfig: microservice-encoder
      spec:
        containers:
          - envFrom:
            image: raduobreja/microservice-encoder-image:latest
            imagePullPolicy: Always
            name: microservice-encoder
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - microservice-encoder
          from:
            kind: ImageStreamTag
            name: microservice-encoder-image:latest
            namespace: default
        type: ImageChange
  