kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    mood-app: microservice-encoder
  name: microservice-encoder
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      mood-app: microservice-encoder
  template:
    metadata:
      labels:
        mood-app: microservice-encoder
    spec:
      containers:
      - name: microservice-encoder
        image: docker.io/raduobreja/microservice-encoder-image:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
